### PR TITLE
Merge repos

### PR DESCRIPTION
**Pull request by DorianCoding**
Hello,

Please find all my changes to sync our repos (the default one and the one with the snap on it). I've corrected the error when there is some API errors, see new messages:

```bash
Cleaning up challenges
Encountered exception during recovery: certbot.errors.PluginError: HTTP Error during request Unauthorized: Missing or invalid API key.
HTTP Error during request Unauthorized: Missing or invalid API key.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
root@vpntls-www:/opt/certbot/lib/python3.12/site-packages/certbot_dns_ionos# certbot certonly --dry-run -v -d vpntls.eu --authenticator dns-ionos --dns-ionos-credentials /etc/letsencrypt/ionos/ionos.ini
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-ionos, Installer None
Simulating a certificate request for vpntls.eu
Performing the following challenges:
dns-01 challenge for vpntls.eu
Cleaning up challenges
Encountered exception during recovery: certbot.errors.PluginError: HTTP Error during request Internal Server Error: A generic error has occurred.
HTTP Error during request Internal Server Error: A generic error has occurred.
```

Thanks.

### CODE REVIEW

**Comment by helgeerbe** [comment]
@DorianCoding you mentioned certbot 3.0.0 but 2.11.0 is the latest release?!

**Comment by DorianCoding** [comment]
https://community.letsencrypt.org/t/certbot-3-0-could-have-potential-third-party-snap-breakages/226940Le 18 oct. 2024 16:12, helgeerbe ***@***.***> a écrit :
@DorianCoding you mentioned certbot 3.0.0 but 2.11.0 is the latest release?!

**Comment by DorianCoding** [comment]
> https://community.letsencrypt.org/t/certbot-3-0-could-have-potential-third-party-snap-breakages/226940Le 18 oct. 2024 16:12, helgeerbe ***@***.***> a écrit : @DorianCoding you mentioned certbot 3.0.0 but 2.11.0 is the latest release?! —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

https://community.letsencrypt.org/t/certbot-3-0-could-have-potential-third-party-snap-breakages/226940

**Comment by helgeerbe** [comment]
Thanks for the link. But this will not work for pip packages. You can't use non existent versions as dependency. The only solution is, to update this plugin, as soon as certbot 3.0.0 is available.

**Comment by DorianCoding** [comment]
> Thanks for the link. But this will not work for pip packages. You can't use non existent versions as dependency. The only solution is, to update this plugin, as soon as certbot 3.0.0 is available.

For snap build is blocked and would unlock when it's okay. I don't know for pip packages. But if you're not synchronized with pip by your Github repo, it could be fine for now. Anyway you can keep the pull open and accept when pip package is updated.

**Pull request merged**
